# Generated by Django 5.1.3 on 2024-12-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_employee_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_joined',
            field=models.DateTimeField(null=True),
        ),
    ]
